"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
              ('images', ['images/']),
              ('templates', ['templates/']),
              ('', ['subscriptions.db']),
]
OPTIONS = {'argv_emulation': False,
           'site_packages': True,
           'includes': ["sip", "PyQt4._qt", "SQLAlchemy", "sqlalchemy-migrate", "jinja2", "chardet", "xlwt", "xlrd", "camelot", "site"],
           'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest',  'PyQt4.QtXml', 'PyQt4.phonon']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
