"""
    Advance Subscription Program: organizes subscription records and generates print reports.
    Copyright (C) 2014, 2015 Max Silbiger.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
              ('images', ['images/']),
              ('templates', ['templates/']),
              ('', ['subscriptions.db']),
]
OPTIONS = {'argv_emulation': False,
           'site_packages': True,
           'includes': ["sip", "PyQt4._qt", "SQLAlchemy", "sqlalchemy-migrate", "jinja2", "chardet", "xlwt", "xlrd", "camelot", "site"],
           'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest',  'PyQt4.QtXml', 'PyQt4.phonon']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
